// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct VaranestClientProgram;
impl sails_rs::client::Program for VaranestClientProgram {}
pub trait VaranestClient {
    type Env: sails_rs::client::GearEnv;
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env>;
    fn declarations(&self) -> sails_rs::client::Service<declarations::DeclarationsImpl, Self::Env>;
    fn trials(&self) -> sails_rs::client::Service<trials::TrialsImpl, Self::Env>;
    fn credentials(&self) -> sails_rs::client::Service<credentials::CredentialsImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> VaranestClient
    for sails_rs::client::Actor<VaranestClientProgram, E>
{
    type Env = E;
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env> {
        self.service(stringify!(Registry))
    }
    fn declarations(&self) -> sails_rs::client::Service<declarations::DeclarationsImpl, Self::Env> {
        self.service(stringify!(Declarations))
    }
    fn trials(&self) -> sails_rs::client::Service<trials::TrialsImpl, Self::Env> {
        self.service(stringify!(Trials))
    }
    fn credentials(&self) -> sails_rs::client::Service<credentials::CredentialsImpl, Self::Env> {
        self.service(stringify!(Credentials))
    }
}
pub trait VaranestClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<VaranestClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> VaranestClientCtors
    for sails_rs::client::Deployment<VaranestClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<VaranestClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod registry {
    use super::*;
    pub trait Registry {
        type Env: sails_rs::client::GearEnv;
        fn register_agent(
            &mut self,
            handle: String,
            description: String,
        ) -> sails_rs::client::PendingCall<io::RegisterAgent, Self::Env>;
        fn update_description(
            &mut self,
            description: String,
        ) -> sails_rs::client::PendingCall<io::UpdateDescription, Self::Env>;
        fn get_agent(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgent, Self::Env>;
        fn get_all_agents(&self) -> sails_rs::client::PendingCall<io::GetAllAgents, Self::Env>;
    }
    pub struct RegistryImpl;
    impl<E: sails_rs::client::GearEnv> Registry for sails_rs::client::Service<RegistryImpl, E> {
        type Env = E;
        fn register_agent(
            &mut self,
            handle: String,
            description: String,
        ) -> sails_rs::client::PendingCall<io::RegisterAgent, Self::Env> {
            self.pending_call((handle, description))
        }
        fn update_description(
            &mut self,
            description: String,
        ) -> sails_rs::client::PendingCall<io::UpdateDescription, Self::Env> {
            self.pending_call((description,))
        }
        fn get_agent(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgent, Self::Env> {
            self.pending_call((owner,))
        }
        fn get_all_agents(&self) -> sails_rs::client::PendingCall<io::GetAllAgents, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(RegisterAgent (handle: String, description: String) -> ());
        sails_rs::io_struct_impl!(UpdateDescription (description: String) -> ());
        sails_rs::io_struct_impl!(GetAgent (owner: ActorId) -> Option<super::Agent>);
        sails_rs::io_struct_impl!(GetAllAgents () -> Vec<super::Agent>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum RegistryEvents {
            AgentRegistered { owner: ActorId, handle: String },
            AgentDescriptionUpdated { owner: ActorId },
        }
        impl sails_rs::client::Event for RegistryEvents {
            const EVENT_NAMES: &'static [Route] = &["AgentRegistered", "AgentDescriptionUpdated"];
        }
        impl sails_rs::client::ServiceWithEvents for RegistryImpl {
            type Event = RegistryEvents;
        }
    }
}

pub mod declarations {
    use super::*;
    pub trait Declarations {
        type Env: sails_rs::client::GearEnv;
        fn declare_capability(
            &mut self,
            claim_text: String,
            category: String,
            stake: u128,
        ) -> sails_rs::client::PendingCall<io::DeclareCapability, Self::Env>;
        fn withdraw_declaration(
            &mut self,
            declaration_id: u64,
        ) -> sails_rs::client::PendingCall<io::WithdrawDeclaration, Self::Env>;
        fn get_agent_declarations(
            &self,
            agent: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgentDeclarations, Self::Env>;
        fn get_all_active(&self) -> sails_rs::client::PendingCall<io::GetAllActive, Self::Env>;
        fn get_declaration(
            &self,
            declaration_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetDeclaration, Self::Env>;
    }
    pub struct DeclarationsImpl;
    impl<E: sails_rs::client::GearEnv> Declarations for sails_rs::client::Service<DeclarationsImpl, E> {
        type Env = E;
        fn declare_capability(
            &mut self,
            claim_text: String,
            category: String,
            stake: u128,
        ) -> sails_rs::client::PendingCall<io::DeclareCapability, Self::Env> {
            self.pending_call((claim_text, category, stake))
        }
        fn withdraw_declaration(
            &mut self,
            declaration_id: u64,
        ) -> sails_rs::client::PendingCall<io::WithdrawDeclaration, Self::Env> {
            self.pending_call((declaration_id,))
        }
        fn get_agent_declarations(
            &self,
            agent: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgentDeclarations, Self::Env> {
            self.pending_call((agent,))
        }
        fn get_all_active(&self) -> sails_rs::client::PendingCall<io::GetAllActive, Self::Env> {
            self.pending_call(())
        }
        fn get_declaration(
            &self,
            declaration_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetDeclaration, Self::Env> {
            self.pending_call((declaration_id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(DeclareCapability (claim_text: String, category: String, stake: u128) -> u64);
        sails_rs::io_struct_impl!(WithdrawDeclaration (declaration_id: u64) -> ());
        sails_rs::io_struct_impl!(GetAgentDeclarations (agent: ActorId) -> Vec<super::CapabilityDeclaration>);
        sails_rs::io_struct_impl!(GetAllActive () -> Vec<super::CapabilityDeclaration>);
        sails_rs::io_struct_impl!(GetDeclaration (declaration_id: u64) -> Option<super::CapabilityDeclaration>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum DeclarationsEvents {
            CapabilityDeclared {
                id: u64,
                agent: ActorId,
                category: String,
            },
            DeclarationWithdrawn {
                id: u64,
            },
        }
        impl sails_rs::client::Event for DeclarationsEvents {
            const EVENT_NAMES: &'static [Route] = &["CapabilityDeclared", "DeclarationWithdrawn"];
        }
        impl sails_rs::client::ServiceWithEvents for DeclarationsImpl {
            type Event = DeclarationsEvents;
        }
    }
}

pub mod trials {
    use super::*;
    pub trait Trials {
        type Env: sails_rs::client::GearEnv;
        fn cast_witness_vote(
            &mut self,
            trial_id: u64,
            verified: bool,
            weight: u32,
        ) -> sails_rs::client::PendingCall<io::CastWitnessVote, Self::Env>;
        fn issue_challenge(
            &mut self,
            declaration_id: u64,
            challenger_stake: u128,
            duration_blocks: u64,
        ) -> sails_rs::client::PendingCall<io::IssueChallenge, Self::Env>;
        fn settle_trial(
            &mut self,
            trial_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleTrial, Self::Env>;
        fn submit_proof(
            &mut self,
            trial_id: u64,
            proof: String,
        ) -> sails_rs::client::PendingCall<io::SubmitProof, Self::Env>;
        fn get_active_trial(
            &self,
            declaration_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetActiveTrial, Self::Env>;
        fn get_all_trials(&self) -> sails_rs::client::PendingCall<io::GetAllTrials, Self::Env>;
        fn get_trial(
            &self,
            trial_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetTrial, Self::Env>;
    }
    pub struct TrialsImpl;
    impl<E: sails_rs::client::GearEnv> Trials for sails_rs::client::Service<TrialsImpl, E> {
        type Env = E;
        fn cast_witness_vote(
            &mut self,
            trial_id: u64,
            verified: bool,
            weight: u32,
        ) -> sails_rs::client::PendingCall<io::CastWitnessVote, Self::Env> {
            self.pending_call((trial_id, verified, weight))
        }
        fn issue_challenge(
            &mut self,
            declaration_id: u64,
            challenger_stake: u128,
            duration_blocks: u64,
        ) -> sails_rs::client::PendingCall<io::IssueChallenge, Self::Env> {
            self.pending_call((declaration_id, challenger_stake, duration_blocks))
        }
        fn settle_trial(
            &mut self,
            trial_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleTrial, Self::Env> {
            self.pending_call((trial_id,))
        }
        fn submit_proof(
            &mut self,
            trial_id: u64,
            proof: String,
        ) -> sails_rs::client::PendingCall<io::SubmitProof, Self::Env> {
            self.pending_call((trial_id, proof))
        }
        fn get_active_trial(
            &self,
            declaration_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetActiveTrial, Self::Env> {
            self.pending_call((declaration_id,))
        }
        fn get_all_trials(&self) -> sails_rs::client::PendingCall<io::GetAllTrials, Self::Env> {
            self.pending_call(())
        }
        fn get_trial(
            &self,
            trial_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetTrial, Self::Env> {
            self.pending_call((trial_id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CastWitnessVote (trial_id: u64, verified: bool, weight: u32) -> ());
        sails_rs::io_struct_impl!(IssueChallenge (declaration_id: u64, challenger_stake: u128, duration_blocks: u64) -> u64);
        sails_rs::io_struct_impl!(SettleTrial (trial_id: u64) -> super::Verdict);
        sails_rs::io_struct_impl!(SubmitProof (trial_id: u64, proof: String) -> ());
        sails_rs::io_struct_impl!(GetActiveTrial (declaration_id: u64) -> Option<super::Trial>);
        sails_rs::io_struct_impl!(GetAllTrials () -> Vec<super::Trial>);
        sails_rs::io_struct_impl!(GetTrial (trial_id: u64) -> Option<super::Trial>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum TrialsEvents {
            ChallengeIssued {
                trial_id: u64,
                declaration_id: u64,
                challenger: ActorId,
            },
            ProofSubmitted {
                trial_id: u64,
                declarer: ActorId,
            },
            WitnessVoted {
                trial_id: u64,
                witness: ActorId,
                verified: bool,
            },
            TrialVerdict {
                trial_id: u64,
                verdict: Verdict,
                rewarded: ActorId,
            },
        }
        impl sails_rs::client::Event for TrialsEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "ChallengeIssued",
                "ProofSubmitted",
                "WitnessVoted",
                "TrialVerdict",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for TrialsImpl {
            type Event = TrialsEvents;
        }
    }
}

pub mod credentials {
    use super::*;
    pub trait Credentials {
        type Env: sails_rs::client::GearEnv;
        fn get_agent_credentials(
            &self,
            agent: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgentCredentials, Self::Env>;
        fn get_credential(
            &self,
            agent: ActorId,
            category: String,
        ) -> sails_rs::client::PendingCall<io::GetCredential, Self::Env>;
        fn get_credentials_by_category(
            &self,
            category: String,
        ) -> sails_rs::client::PendingCall<io::GetCredentialsByCategory, Self::Env>;
        fn get_verified_agents(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetVerifiedAgents, Self::Env>;
    }
    pub struct CredentialsImpl;
    impl<E: sails_rs::client::GearEnv> Credentials for sails_rs::client::Service<CredentialsImpl, E> {
        type Env = E;
        fn get_agent_credentials(
            &self,
            agent: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgentCredentials, Self::Env> {
            self.pending_call((agent,))
        }
        fn get_credential(
            &self,
            agent: ActorId,
            category: String,
        ) -> sails_rs::client::PendingCall<io::GetCredential, Self::Env> {
            self.pending_call((agent, category))
        }
        fn get_credentials_by_category(
            &self,
            category: String,
        ) -> sails_rs::client::PendingCall<io::GetCredentialsByCategory, Self::Env> {
            self.pending_call((category,))
        }
        fn get_verified_agents(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetVerifiedAgents, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(GetAgentCredentials (agent: ActorId) -> Vec<super::Credential>);
        sails_rs::io_struct_impl!(GetCredential (agent: ActorId, category: String) -> Option<super::Credential>);
        sails_rs::io_struct_impl!(GetCredentialsByCategory (category: String) -> Vec<super::Credential>);
        sails_rs::io_struct_impl!(GetVerifiedAgents () -> Vec<ActorId>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum CredentialsEvents {
            CredentialMinted {
                agent: ActorId,
                category: String,
                level: BadgeLevel,
                trial_id: u64,
            },
        }
        impl sails_rs::client::Event for CredentialsEvents {
            const EVENT_NAMES: &'static [Route] = &["CredentialMinted"];
        }
        impl sails_rs::client::ServiceWithEvents for CredentialsImpl {
            type Event = CredentialsEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Agent {
    pub handle: String,
    pub owner: ActorId,
    pub description: String,
    pub active: bool,
    pub registration_block: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct CapabilityDeclaration {
    pub id: u64,
    pub agent: ActorId,
    pub claim_text: String,
    pub category: String,
    pub stake: u128,
    pub status: DeclarationStatus,
    pub timestamp: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum DeclarationStatus {
    Active,
    Challenged,
    Verified,
    Failed,
    Withdrawn,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Verdict {
    Pending,
    Verified,
    Failed,
    Expired,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Trial {
    pub id: u64,
    pub declaration: u64,
    pub declarer: ActorId,
    pub challenger: ActorId,
    pub declarer_stake: u128,
    pub challenger_stake: u128,
    pub deadline: u64,
    pub proof: Option<String>,
    pub witness_votes: Vec<WitnessVote>,
    pub verdict: Verdict,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct WitnessVote {
    pub witness: ActorId,
    pub verified: bool,
    pub weight: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Credential {
    pub agent: ActorId,
    pub category: String,
    pub level: BadgeLevel,
    pub trial_id: u64,
    pub minted_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BadgeLevel {
    Bronze,
    Silver,
    Gold,
}
